Rails.application.routes.draw do
  root 'home#index'
  resources :posts, path: 'postagens'
  resources :actions, path: 'acoes-urbanas'
  resources :mobilizations, path: 'mobilizacao'
  resources :social_events, path: 'eventos-sociais'
  get 'termos_de_uso',           to: 'custom_pages#terms'
  get 'ouvidoria',               to: 'custom_pages#ouvidoria'
  get 'selagem',                 to: 'sealings#index'
  get 'acessoainformacao',       to: 'custom_pages#info'
  get 'link_download',           to: 'custom_pages#link_download'
  get 'passoapasso',             to: 'custom_pages#passoapasso'

  resources :social_events, path: 'eventos-sociais'
  get '/acoes_concluidas', to: 'actions#done_action'
  get 'galeria', to: 'actions#galeria'
  get 'habitabrasilia', to: 'custom_pages#habita'

  get 'agendamentos_habitacao', to: 'schedules#habitacao'
  resources :technical_assistances, path: 'assistencia-tecnica'
  resources :actions, path: 'acoes-urbanas'
  resources :social_events, path: 'eventos-sociais'

  get 'postos' ,                   to: 'technical_assistances#station'
  get 'melhorias' ,                to: 'technical_assistances#improvement'
  get 'termos_de_uso',             to: 'custom_pages#terms'
  get 'ouvidoria',                 to: 'custom_pages#ouvidoria'
  get 'selagem',                   to: 'sealings#index'
  get 'acessoainformacao',         to: 'custom_pages#info'
  get 'portas_abertas',            to: 'custom_pages#portas_abertas'
  get 'link_download',             to: 'custom_pages#link_download'
  get 'passoapasso',               to: 'custom_pages#passoapasso'
  get 'recuperacao_senha',         to: 'custom_pages#recuperacao_senha'
  get 'selagemcrixa_area1',        to: 'custom_pages#selagemcrixa_area1'
  get 'selagemcrixa_area2',        to: 'custom_pages#selagemcrixa_area2'
  get 'selagemcrixa_area3',        to: 'custom_pages#selagemcrixa_area3'
  get 'selagemcrixa_area4',        to: 'custom_pages#selagemcrixa_area4'
  get 'selagemcrixa_area5',        to: 'custom_pages#selagemcrixa_area5'
  get 'selagemcrixa_area6',        to: 'custom_pages#selagemcrixa_area6'
  get 'selagem_crixa',             to: 'custom_pages#selagem_crixa'
  get 'selagem_bonsucesso_area1',  to: 'custom_pages#selagem_bonsucesso_area1'
  get 'selagem_bonsucesso_area2',  to: 'custom_pages#selagem_bonsucesso_area2'
  get 'selagem_bonsucesso_area3',  to: 'custom_pages#selagem_bonsucesso_area3'
  get 'selagem_bonsucesso_area4',  to: 'custom_pages#selagem_bonsucesso_area4'
  get 'selagem_bonsucesso',        to: 'custom_pages#selagem_bonsucesso'
  get 'selagem_bananal',           to: 'custom_pages#selagem_bananal'
  get 'selagem_bananal_area1',     to: 'custom_pages#selagem_bananal_area1'
  get 'selagem_copaibas',          to: 'custom_pages#selagem_copaibas'
  get 'selagem_copaibas_area1',    to: 'custom_pages#selagem_copaibas_area1'
  get 'acoes-concluidas',          to: 'actions#done_action'
  get 'galeria',                   to: 'actions#galeria'

end
